default:
  outputs:

    dev:
      type: redshift
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [dev_username]
      pass: [dev_password]
      dbname: [dbname]
      schema: [dev_schema]

    prod:
      type: redshift
      method: iam
      cluster_id: [cluster_id]
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_user]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev

jaffle_shop: # this needs to match the profile: in your dbt_project.yml file
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: dbt-demos # Replace this with your project id
      dataset: dbt_blake # Replace this with dbt_your_name, e.g. dbt_bob
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
      keyfile_json:
        type: "service_account"
        project_id: "dbt-demos"
        private_key_id: "{{ env_var('PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('PRIVATE_KEY') }}"
        client_email: "{{ env_var('CLIENT_EMAIL') }}"
        client_id: "{{ env_var('CLIENT_ID') }}"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        client_x509_cert_url: "{{ env_var('CLIENT_CERT_URL') }}"